version: "3.9"
services:
  postgres:
    image: postgres:13
    volumes:
      - ./tmp/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ENV['APPLICATION_NAME_DEV_PASSWORD']
      POSTGRES_USER: ENV['APPLICATION_NAME_DEV_USERNAME']
      POSTGRES_DB: ENV['APPLICATION_NAME_DEV_DATABASE']
    ports:
      - "5433:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/APPLICATION_NAME
    ports:
      - "3000:3000"
    depends_on:
      - postgres